#!/bin/bash
set -e
#set -o pipefail

cd "${1}"
dir=`pwd`
PATH=/usr/local/bin:$PATH
exec 3>&1
exec 1>&2

echo $dir >&3
payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0
timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
text="$(jq -r '.params.text' < "${payload}")"

debug_info="$(cat <<EOF
{
  "Message": "${text}"
}
EOF
)"
echo "$debug_info" | jq -s add  >&3
