#!/bin/bash
set -e
#set -o pipefail

cd "${1}"

exec 3>&1
exec 1>&2


payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0
timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
text="$(jq -r '.params.text' < "${payload}")"

echo "$timestamp $text" | jq -s add  >&3
